version: "3.9"
services:
  web:
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      DB_NAME: ${DB_NAME}
      COLLECTION_NAME: ${COLLECTION_NAME}
      MONGO_DB_URL: ${MONGO_DB_URL}
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
